"""Save Tables

Revision ID: 22e4bb337e5a
Revises: 5dcd6a1ea075
Create Date: 2021-08-25 23:05:04.524126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e4bb337e5a'
down_revision = '5dcd6a1ea075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'text')
    # ### end Alembic commands ###
