"""Save Tables

Revision ID: 5dcd6a1ea075
Revises: 9953f91057e6
Create Date: 2021-08-25 23:04:11.073223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dcd6a1ea075'
down_revision = '9953f91057e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
