"""Save Tables

Revision ID: 654b91e467c9
Revises: d00670ddb5a2
Create Date: 2021-08-25 23:11:04.770265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654b91e467c9'
down_revision = 'd00670ddb5a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
