"""categories

Revision ID: 82bc587b5b6f
Revises: 38e49ceeff89
Create Date: 2021-08-16 12:25:08.828095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bc587b5b6f'
down_revision = '38e49ceeff89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('username', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'pitches', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='unique')
    op.drop_column('pitches', 'username')
    # ### end Alembic commands ###
