"""Save Tables

Revision ID: 9aa721c5fc0b
Revises: e1441d62ae6e
Create Date: 2021-08-25 16:17:56.513757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa721c5fc0b'
down_revision = 'e1441d62ae6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('vcsh', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'vcsh')
    # ### end Alembic commands ###
