"""Save Tables

Revision ID: c8d62ef7b2f6
Revises: 9aa721c5fc0b
Create Date: 2021-08-25 16:20:23.893167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d62ef7b2f6'
down_revision = '9aa721c5fc0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'vygd')
    op.drop_column('pitches', 'vcsh')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('vcsh', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('vygd', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
