"""Save Tables

Revision ID: d3a373cf12ad
Revises: de2032b33967
Create Date: 2021-08-25 16:12:59.289301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a373cf12ad'
down_revision = 'de2032b33967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'vygd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('vygd', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
