"""Save Tables

Revision ID: e1441d62ae6e
Revises: d3a373cf12ad
Create Date: 2021-08-25 16:14:53.990148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1441d62ae6e'
down_revision = 'd3a373cf12ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('vygd', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'vygd')
    # ### end Alembic commands ###
